### ISSUE TITLE
Update request.

### ISSUE THREAD

**Issue by mgiannopoulos24** [Kracken256/ssh-keyfinder#1]
Hey there,
I would like to ask if you can update your script in order to extract keys from the core file only but especially when the key comment isn't know. 

Please contact me on Discord (deathwish.xxiv). I made a script and I would like to ask if theres a better way to detect keys in dump.

Thanks in advance.

**Comment by Kracken256** [comment]
Hi. I can't find your discord contact. DM me on discord via @kracken256
